### ISSUE TITLE
About result data

### ISSUE THREAD

**Issue by chengmingjiang** [nghiavtr/SCmut#6]
Hi SCmut team，
I am particularly interested in your tool. For these four result files, I would like to ask you the same question. 
![image](https://user-images.githubusercontent.com/42594736/153589893-250d9fd9-a150-4b96-b1a4-da9e5aea23aa.png)
Take BC03 as an example, do C1-C33 in your result file correspond to BC03_01 to BC03_33 in the original data? If not, can you please provide the corresponding relationship between the cells and the cell numbers of the original data?
![image](https://user-images.githubusercontent.com/42594736/153588889-602380f6-2c6b-4ba2-a63a-8409e4840f1b.png)

Looking forward to your guidance, thank you!

**Comment by nghiavtr** [comment]
Hi @chengmingjiang,

Thank you for interesting SCmut in your research. The column names of the files "C1-C33" were randomized, so not correspond to BC03_01 to BC03_33 of the original data.

Please give drop me a line  to my email (TrungNghia.Vu@ki.se), I will provide the data you need.

Best,
Nghia

**Comment by chengmingjiang** [comment]
Hi Nghia, 

Thank you for your enthusiastic help, the relevant data information has been received and my problem has been solved.

Best,
Cheng

**Comment by mugpeng** [comment]
Hi Nghia,

I am questioned about how to obtain the following single cell mut matrix from `scfdr` output or any other steps.
![image](https://user-images.githubusercontent.com/52995448/204979991-c08130c4-32ea-4d9a-9b16-44bfcd8a5699.png)

Because it seems like the tutorial script only select the filtered mut from a cell as an vector class. Should I find the filtered index at the original single cell mut matrix to generate the above files?

Thanks.

**Comment by nghiavtr** [comment]
Hi @mugpeng 
Thank you for using scMut in your research.

To run scMut, we need a vector mut.sites containing a list of candidate somatic mutations which will be used for filtering to keep only ones with significant fdr2d. So you need to provide this mutation list and the mutations in the list must be found in the original single cell mut matrix.

The files above (in SCmut_mutations) are the results of scMut after filtering the candidates in the mutation list with fdr2d < 0.2.

Nghia

**Comment by mugpeng** [comment]
cool. Thank you.
